# This rule is not used by the project sandbox-k8s itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sandbox.opensandbox.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sandbox-k8s
    app.kubernetes.io/managed-by: kustomize
  name: pool-admin-role
rules:
- apiGroups:
  - sandbox.opensandbox.io
  resources:
  - pools
  verbs:
  - '*'
- apiGroups:
  - sandbox.opensandbox.io
  resources:
  - pools/status
  verbs:
  - get
